version: '3'

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - ./data/docker/volumes/mysql/:/var/lib/mysql

  stellar:
    image: stellar/quickstart:testing
    container_name: stellar
    ports:
      - '8000:8000'
      - '8001:8001'
    command: ['--standalone']
