name: CI Workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  run-tests:
    env:
      PORT: 3000
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USERNAME: test
      DB_PASSWORD: test
      DB_NAME: test
      SONAR_SERVER_URL: test
      SONAR_TOKEN: test
      STELLAR_NETWORK: testnet
      STELLAR_ISSUER_SECRET_KEY: FAKE_SECRET_KEY
      STELLAR_DISTRIBUTOR_SECRET_KEY: FAKE_SECRET_KEY
      STELLAR_CONFIRM_SECRET_KEY: FAKE_SECRET_KEY
      STELLAR_CONSOLIDATE_SECRET_KEY: FAKE_SECRET_KEY
      STELLAR_DELIVER_SECRET_KEY: FAKE_SECRET_KEY

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0

      - name: Build
        run: |
          npm run lint
          npm run format
          npm run build
          npm run test:cov
